export const navItems = [
  { id: "notices", title: "Notices" },
  { id: "shareholder-meeting", title: "Shareholder Meeting" },
  { id: "qip", title: "Qualified Institutions Placement" },
  { id: "intimation-board-meeting", title: "Intimation Of Board Meeting" },
  { id: "investor-outcome", title: "Investor Outcome" },
  { id: "investor-meet", title: "Investor Meet" },
  { id: "press-release", title: "Press Release" },
  { id: "investor-presentation", title: "Investor Presentation" },
  { id: "board-meeting", title: "Board Meeting" },
  { id: "concall-meeting", title: "Concall Meeting" },
  { id: "annual-returns", title: "Annual Returns" },
  { id: "annual-reports", title: "Annual Reports" },
  { id: "code-policies", title: "Code & Policies" },
  { id: "code-of-conduct", title: "Code of Conduct" },
  { id: "share-holding-pattern", title: "Share Holding Pattern" },
  { id: "sdd", title: "Structured Digital Database" },
  { id: "committees", title: "Committees of Board of Director" },
  { id: "half-yearly-results", title: "Half Yearly Results 2023-24" },
  { id: "intimation-disclosures-sebi-lodr", title: "Intimation And Disclosures Under Reg 29 And 30 Of SEBI Lodr" },
  { id: "info-sebi-lodr-reg-2015", title: "Information pursuant to SEBI (LODR) Regulation, 2015" },
  { id: "financial-statement-subsidiary", title: "Financial Statement of Subsidiary companies" },
  { id: "financial-results", title: "Financial Results" },
  { id: "related-party-transaction", title: "Disclosure of Related Party Transaction" },
  { id: "corporate-governance-report", title: "Corporate Governance Report" },
];
